# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - flaskml-sulav-predict

trigger:
  branches:
    include:
      - master 
  paths:
    include:
      - 'CI-CD-Pipeline-Azure-Devops/*'

variables:
  azureServiceConnectionID: '456cc604-544c-45f8-99d0-c1b73aeec440'

  webAppName: 'flaskml-sulav-predict'

  vmImageName: 'ubuntu-latest'

  projectRoot: $(System.DefaultWorkingDirectory)
  
  pythonVersion: 3.9

  environmentName: 'flasml-sulav-predict'

  workspaceDirL: 'CI-CD-Pipeline-Azure-Devops' 


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        pwd
        ls -la
      workingDirectory: $(projectRoot)/$(workspaceDir)
      displayName: "Verify build environment"
    
    - script: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)/$(workspaceDir)
      displayName: "Install requirements"
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)/$(workspaceDir)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop


- stage: Deploy
  displayName: 'Deploy Web App CD'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : flaskml-sulav-predict'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
